config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "base#index"
    resources :words, except: :show 
    resources :courses, except: :show
    resources :users, except: :show
    resources :questions, except: :show
    post "/import-words", to: "imports#import_words"
    post "/import-questions", to: "imports#import_questions"
  end
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :courses, only: %(index)
  resources :exercises
  resources :password_resets, only: %i(new create edit update)
  get "/facebook/login", to: "facebooks#login_facebook", as: "login_facebook"
  resource :facebook
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "word-learned", to:"words#view_word", as: "view_word"
end

app/models/supports/word.rb
class Supports::Word
  attr_reader :course, :page

  def initialize course, page
    @course = course
    @page = page
  end

  def load_words
    @course.words.page(@page).per Settings.words.learning.paging_number
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :course
  has_many :questions, dependent: :destroy
  has_many :learnings, dependent: :destroy
  validates :name, presence: true,
    length: {maximum: Settings.words.name.max_length}
  validates :pronounce, presence: true,
    length: {maximum: Settings.words.pronounce.max_length}
  validates :meaning, presence: true

  WORD_PARAMS = %i(name pronounce meaning course_id example).freeze

  delegate :name, to: :course, prefix: true, allow_nil: true

  class << self
    def import_word file
     data_words = []

      CSV.foreach(file.path, headers: true) do |row|
        data_words << {name: row["name"], meaning: row["meaning"],
          course_id: row["couse_id"], pronounce: row["pronounce"],
          example: row["example"] }
      end
      
      ActiveRecord::Base.transaction do
        Word.create data_words
      end
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < Admin::BaseController
  before_action :load_word, except: %i(index new create)
  
  def index
    @words = Word.order(created_at: :desc).page(params[:page])
      .per Settings.words.paging.page_nummber
  end

  def new
    @word = Word.new
  end

  def create 
    @word = Word.new word_params

    if @word.save
      flash[:success] = t ".success_created"
      redirect_to admin_words_path
    else
      flash[:danger] = t ".fail_create"
      render :new
    end
  end

  def update
    if @word.update word_params
      flash[:success] = t ".success_updated"
      redirect_to admin_words_path
    else
      flash[:fail] = t ".fail_update"
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t ".success_destroyed"
    else
      flash[:danger] = t ".fail_destroy"
    end
    redirect_to admin_words_path
  end

  private
  
  def word_params
    params.require(:word).permit Word::WORD_PARAMS
  end

  def load_word
    @word = Word.find_by id: params[:id]

    return if @word
    flash[:danger] = t ".not_found"
    redirect_to admin_words_path
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user
  
  def index
    course = Course.find_by id: params[:course_id]
    
    if course.present?
      @supports = Supports::Word.new course, params[:page]
      
      return if @supports.load_words.empty?
      LearningService.new(current_user, @supports.load_words.first).mark_learned
    else
      flash[:danger] = t ".not_found"
      redirect_to root_path
    end
  end
  
  def view_word
    @learnings = current_user.learnings.includes(:word).page(params[:page]).per Settings.words.learning.paging_number
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def load_courses
    Course.pluck :name, :id
  end
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :meaning %>
  <%= f.text_field :meaning, class: "form-control" %>
  <%= f.label :pronounce %>
  <%= f.text_field :pronounce, class: "form-control" %>
  <%= f.label :example %>
  <%= f.text_area :example, class: "form-control" %>
  <%= f.label :course %>
  <%= f.select :course_id, options_for_select(load_courses, selected: @word.course_id), {}, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary my-2" %>
<% end %>

app/views/admin/words/_word.html.erb
<tr >
  <td><%= index_of_list @words, word_counter %></td>
  <td><%= word.name %></td>
  <td><%= word.meaning %></td>
  <td><%= word.course_name %></td>
  <td>
    &ensp; 
    <%= link_to edit_admin_word_path(word), class: "btn btn-warning" do %>
      <i class="fa fa-edit"></i>
    <% end %>
    &ensp;
    <%= link_to admin_word_path(word), method: :delete,
      data: { confirm: t(".are_you_sure?") }, class: "btn btn-danger" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, t(".word_edit") %>
<%= provide :button_text, t(".save") %>
<div class="row justify-content-center">
  <div class="col-10">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t(".word") %>
<div class="row">
  <div class="col-md-12">
    <%= link_to new_admin_word_path, class: "btn btn-outline-primary mb-3" do %>
      <i class="fa fa-plus"></i>
      <%=  t ".create_word" %>
    <% end %>
    <%= form_tag admin_import_words_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag t(".import"), class: "btn btn-outline-info" %>
    <% end %>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"><%= t ".word_list" %></h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered w-100" cellsapcing="0">
            <tr>
              <thead>
                <th><%= t ".stt" %></th>
                <th><%= t ".name" %></th>
                <th><%= t ".meaning" %></th>
                <th><%= t ".course" %></th>
                <th><%= t ".action" %></th>
              </thead>
            </tr>
            <tbody>
              <%= render partial: "word", collection: @words, as: :word  %>
            </tbody>
          </table>
          <%= paginate @words, theme: Settings.theme.paging %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t(".add_word") %>
<%= provide :button_text, t(".add_word") %>
<div class="row justify-content-center">
  <div class="col-10">
    <%= render "form" %>
  </div>
</div>