config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "base#index"
    resources :words, except: :show 
    resources :courses, except: :show
    resources :users, except: :show
    resources :questions, except: :show
    post "/import-words", to: "imports#import_words"
    post "/import-questions", to: "imports#import_questions"
  end
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :courses, only: %(index)
  resources :exercises
  resources :password_resets, only: %i(new create edit update)
  get "/facebook/login", to: "facebooks#login_facebook", as: "login_facebook"
  resource :facebook
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "word-learned", to:"words#view_word", as: "view_word"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  has_many :exercises, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :learnings, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  VALID_EMAIL_REGEX = Settings.users.email.regex
  VALID_PASSWORD_REGEX = Settings.users.password.regex
  validates :name, presence: true,
    length: {minimum: Settings.users.name.min_length,
    maximum: Settings.users.name.max_length}
  validates :email, presence: true,
    length: {maximum: Settings.users.email.max_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: Settings.users.password.min_length,
    maximum: Settings.users.password.max_length},
    format: {with: VALID_PASSWORD_REGEX}, allow_nil: true
  has_one_attached :avatar
  
  USER_PARAMS = %i(name email avatar password password_confirmation).freeze
  ADMIN_USER_PARAMS = %i(name email avatar password password_confirmation is_admin).freeze

  has_secure_password

  def authenticated? attribute, token
    digest = self.send("#{attribute}_digest")
    return false unless digest
    BCrypt::Password.new(digest).is_password? token
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now
  end

  def password_reset_expired?
    reset_sent_at < Settings.users.reset_sent_at.expired_time.hours.ago
  end

  def activate
    update activated: true, activated_at: Time.zone.now
  end

  def forget
    update remember_digest: nil
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: %i(index new create)

  def index
    @users = User.order(created_at: :desc).page(params[:page])
      .per Settings.users.paging.paging_number
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = t ".success_created"
      redirect_to admin_users_path
    else
      flash[:dange] = t ".fail_create"
      render :new
    end
  end

  def update
    if @user.update user_params
      flash[:success] = t ".success_updated"
      redirect_to admin_users_path
    else
      flash[:danger] = t ".fail_update"
      render :new
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".success_destroyed"
    else
      flash[:fail] = t ".fail_destroy"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit User::ADMIN_USER_PARAMS
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t ".not_found"
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new create show)
  before_action :load_user, except: %i(index new create)

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      @user.send_activation_email
      flash[:info] = t ".please_check_mail"
      redirect_to @user
    else
      flash[:fail] = t ".fail_create"
      render :new
    end
  end

  def update
    if @user.update user_params
      flash[:success] = t ".update_success"
      redirect_to @user
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit User::USER_PARAMS
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t ".not_found"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def build_relationship
    current_user.active_relationships.build
  end
  
  def load_relationship user_id
    current_user.active_relationships.find_by followed_id: user_id
  end

  def load_avatar user
    avatar = user.avatar.attached? ? user.avatar : Settings.users.avatar
  end
end

app/views/users/_follow.html.erb
<%= form_for build_relationship, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow"), class: "btn btn-outline-primary", id: "follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user)%>
  <div id="form_follow">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.label :avatar %>
  <%= f.file_field :avatar, class: "btn btn-outline-primary btn-sm btn-block" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block"  %>
  <%= t ".already_account" %>
  <%= link_to  t(".login"), login_path, class: "btn btn-link" %>
<% end %>

app/views/users/_form_follow.html.erb
<% unless current_user?(@user)%>
  <div id="form_follow">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for load_relationship(@user.id),
  html: {method: :delete}, remote: true do |f| %>
  <%= f.submit t(".unfollow"), class: "btn btn-outline-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% avatar = user.avatar.attached? ? user.avatar : "Rose.jpg" %>
  <%= link_to image_tag(avatar), user_path(user) %>
  <%= user.name %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".edit_profile") %>
<%= provide :button_text, t(".change_profile") %>
<h1><%= t ".edit_profile" %></h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".signup") %>
<%= provide :button_text, t(".create") %>
<h1><%= t ".signup" %></h1>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="details_container">
    <div class="row">
      <div class="row">
        <div class="col">
          <div class="courses_title"><%= @user.name %></div>
            <%= image_tag load_avatar(@user), size: Settings.users.size %>
            <%= render "shared/stats" %>
          </div>
        </div>
        <div class="col">
          <% if !current_user?(@user) %>
            <%= render "form_follow" %>
          <% else %>
            <%= link_to t(".edit"), edit_user_path, class:"btn btn-primary btn-edit" %>
            &ensp;
            <%= link_to t(".learned_word", quantity: @user.learnings.size), view_word_path, class:"btn btn-primary btn-edit" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>