config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: "base#index"
    resources :words, except: :show 
    resources :courses, except: :show
    resources :users, except: :show
    resources :questions, except: :show
    post "/import-words", to: "imports#import_words"
    post "/import-questions", to: "imports#import_questions"
  end
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :courses, only: %(index)
  resources :exercises
  resources :password_resets, only: %i(new create edit update)
  get "/facebook/login", to: "facebooks#login_facebook", as: "login_facebook"
  resource :facebook
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "word-learned", to:"words#view_word", as: "view_word"
end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
        <% image = current_user.avatar.attached? ? current_user.avatar : "default" %>
        <%= image_tag image, class: "img-profile rounded-circle w-40" %>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <%= link_to admin_path, class: "dropdown-item" do %>
          <i class="fa fa-home fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t ".dashboard" %>
        <% end %>
        <%= link_to current_user, class: "dropdown-item" do %>
          <i class="fa fa-user fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t ".profile" %>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to user_path(current_user), method: :delete, class: "dropdown-item" do %>
          <i class="fa fa-sign-out fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t(".sign_out") %>
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_admin_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <hr class="sidebar-divider my-0">

  <li class="nav-item active">
      <%= link_to admin_path, class: "nav-link"  do %>
      <i class="fa fa-fw fa-tachometer-alt"></i>
      <label><%= t ".dashboard" %></label>
      <% end %>
  </li>

  <hr class="sidebar-divider">

  <div class="sidebar-heading">
  </div>

  <li class="nav-item">
    <%= link_to admin_users_path, class: "nav-link collapsed" do %>
      <i class="fa fa-fw fa-user"></i>
      <label><%= t ".user" %></label>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to admin_courses_path, class: "nav-link collapsed" do %>
      <i class="fa fa-fw fa-cog"></i>
      <label><%= t".course" %></label>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_words_path, class: "nav-link" do %>
      <i class="fa fa-fw fa-file-word-o"></i>
      <label><%= t ".manage_words" %></label>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_questions_path, class: "nav-link" do %>
      <i class="fa fa-fw fa-question-circle"></i>
      <label><%= t ".manage_questions" %></label>
    <% end %>
  </li>
</ul>

app/views/layouts/_header.html.erb
<header class="header">
  <!-- Header Content -->
  <div class="header_container">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header_content d-flex flex-row
            align-items-center justify-content-start">
            <div class="logo_container">
              <a href=<%= root_path %>>
                <div class="logo_text"><%= t".ht" %>
                  <span><%= t".edu" %></span></div>
              </a>
            </div>
            <nav class="main_nav_contaner ml-auto">
              <ul class="main_nav">
                <div id="menu">
                <li class="link active">
                  <%= link_to t(".home"), root_path %>
                </li>
                <% if logged_in? %>
                  <li class="link"><%= link_to t(".exercise"), exercises_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= t ".user" %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item"><%= link_to t(".profile"), current_user %></li>
                      <div class="dropdown-divider"></div>
                      <li class="dropdown-item">
                        <%= link_to t(".logout"), logout_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
                  <div class="search_button"><i class="fa fa-search"
                   aria-hidden="true"></i></div>
                <% else %>
                  <li class="link">
                    <%= link_to t(".login"), login_path %>
                  </li>
                <% end %>
              </div>
              </ul>
              <!-- Hamburger -->
            </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  <!-- Header Search Panel -->
  <div class="header_search_container">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header_search_content d-flex flex-row align-items-center justify-content-end">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="Search" placeholder="Search"
                aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                <%= t ".search" %>
              </button>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

app/views/layouts/_scroll_top.html.erb
<%= link_to "#page-top", class: "scroll-to-top rounded" do %>
  <i class="fa fa-angle-up"></i>
<% end %>

app/views/layouts/_shim.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/shim" %>
  </head>

  <body id="page-top">
    <div id="wrapper">
      <%= render "layouts/admin_sidebar" %>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render "layouts/admin_navbar" %>
            <%= render "shared/flash" %>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="logoutModal" tabindex="-1"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              <%= t ".ready_to_leave" %>
            </h5>
            <button class="close" type="button" data-dismiss="modal"
             aria-label="Close">
              <span aria-hidden="true">x</span> 
            </button>
          </div>
          <div class="modal-body"><%= t ".select_logout_below" %></div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button"
             data-dismiss="modal">
              <%= t ".cancel" %>
            </button>
            <%= link_to "logout_path", class: "dropdown-item" do %>
              <%= t ".logout" %>
            <% end %>
          </div>
        </div>
      </div> 
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>